version: '3.9'

services:
  product-main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: product-main-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://main-app:8000/healthcheck/"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
