version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: main-postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - ../.env
    command:
      -p ${DB_PORT}
volumes:
  postgres_data:
