"""Add User.deleted_add field

Revision ID: 2c7051bb0ddd
Revises: 9a25c53c6130
Create Date: 2024-06-27 22:16:50.999600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7051bb0ddd'
down_revision = '9a25c53c6130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True))
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
