"""Add ProductModel

Revision ID: c41093a3802b
Revises: 2a1a67583847
Create Date: 2024-06-30 16:31:06.853623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41093a3802b'
down_revision = '2a1a67583847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
